# Netlify configuration file
[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

# Create data directory during build
[build.environment]
  CREATE_DATA_DIR = "true"

# Redirects for API endpoints to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect for SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200