# Netlify configuration file
[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

# Create data directory during build
[build.environment]
  CREATE_DATA_DIR = "true"
  NODE_ENV = "production"
  # Map React app environment variables to function environment variables
  FIREBASE_STORAGE_BUCKET = "${REACT_APP_FIREBASE_STORAGE_BUCKET}"

# Set node.js version for functions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# Scheduled function for updating place data every 72 hours
[functions."scheduled-places-update"]
  schedule = "0 0 */3 * *"
  # Increased timeout for function as it may need to process many locations
  timeout = 120

# Individual function configuration for manual update
[functions."force-places-update"]
  # Increased timeout for function as it may need to process many locations
  timeout = 120

# Configuration for photo migration function
[functions."migrate-new-photos"]
  # Increased timeout for function as it may need to download and upload many images
  timeout = 300
  # Ensure environment variables are properly set
  [functions."migrate-new-photos".environment]
    NODE_ENV = "production"

# Configuration for background function to store photos for a single location
[functions."store-location-photos-background"]
  # Increased timeout for background function (max 15 minutes = 900 seconds)
  timeout = 900
  # Ensure environment variables are properly set
  [functions."store-location-photos-background".environment]
    NODE_ENV = "production"

# Redirects for API endpoints to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Explicitly serve static files with higher priority
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Catch-all redirect for SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration for background function to delete photos for a single location
[functions."delete-location-photos-background"]
  # Increased timeout for background function (max 15 minutes = 900 seconds)
  timeout = 900
  # Ensure environment variables are properly set
  [functions."delete-location-photos-background".environment]
    NODE_ENV = "production"